package com.proj.bean;
// Generated Nov 20, 2016 9:57:49 PM by Hibernate Tools 4.3.1



/**
 * ProjGroup generated by hbm2java
 */
public class ProjGroup  implements java.io.Serializable {


     private int groupid;
     private Project project;
     private User user;
     private boolean isAdmin;
     private String status;

    public ProjGroup() {
    }

    public ProjGroup(int groupid, Project project, User user, boolean isAdmin, String status) {
       this.groupid = groupid;
       this.project = project;
       this.user = user;
       this.isAdmin = isAdmin;
       this.status = status;
    }
   
    public int getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(int groupid) {
        this.groupid = groupid;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


