package com.proj.bean;
// Generated Nov 20, 2016 9:57:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private int projid;
     private User user;
     private String projtitle;
     private String projdesc;
     private Set<Task> tasks = new HashSet<Task>(0);
     private Set<ProjGroup> projGroups = new HashSet<ProjGroup>(0);

    public Project() {
    }

	
    public Project(int projid, User user, String projtitle) {
        this.projid = projid;
        this.user = user;
        this.projtitle = projtitle;
    }
    public Project(int projid, User user, String projtitle, String projdesc) {
        this.projid = projid;
        this.user = user;
        this.projtitle = projtitle;
        this.projdesc = projdesc;
    }
    public Project(int projid, User user, String projtitle, String projdesc, Set<Task> tasks, Set<ProjGroup> projGroups) {
       this.projid = projid;
       this.user = user;
       this.projtitle = projtitle;
       this.projdesc = projdesc;
       this.tasks = tasks;
       this.projGroups = projGroups;
    }

    public void printObject() {
        System.out.println( "Project{" + "projid=" + projid + ", user=" + user + ", projtitle=" + projtitle + ", projdesc=" + projdesc + ", tasks=" + tasks + ", projGroups=" + projGroups + '}');
    }
  
    public int getProjid() {
        return this.projid;
    }
    
    public void setProjid(int projid) {
        this.projid = projid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getProjtitle() {
        return this.projtitle;
    }
    
    public void setProjtitle(String projtitle) {
        this.projtitle = projtitle;
    }
    public String getProjdesc() {
        return this.projdesc;
    }
    
    public void setProjdesc(String projdesc) {
        this.projdesc = projdesc;
    }
    public Set<Task> getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }
    public Set<ProjGroup> getProjGroups() {
        return this.projGroups;
    }
    
    public void setProjGroups(Set<ProjGroup> projGroups) {
        this.projGroups = projGroups;
    }




}


