package com.proj.bean;
// Generated Nov 20, 2016 9:57:49 PM by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SubTask generated by hbm2java
 */
public class SubTask  implements java.io.Serializable {

     private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

     private int subtaskid;
     private Task task;
     private User user;
     private String subtitle;
     private String subdesc;
     private String actiondesc;
     private Date actiontime;
     private Set<Tag> tags = new HashSet<Tag>(0);

    public SubTask() {
    }

	
    public SubTask(int subtaskid, Task task, User user, String subtitle, String subdesc, String actiondesc) {
        this.subtaskid = subtaskid;
        this.task = task;
        this.user = user;
        this.subtitle = subtitle;
        this.subdesc = subdesc;
        this.actiondesc = actiondesc;
        this.actiontime = new Date();
    }
    public SubTask(int subtaskid, Task task, User user, String subtitle, String subdesc, String actiondesc, Set<Tag> tags) {
       this.subtaskid = subtaskid;
       this.task = task;
       this.user = user;
       this.subtitle = subtitle;
       this.subdesc = subdesc;
       this.actiondesc = actiondesc;
       this.actiontime = new Date();
       this.tags = tags;
    }
   
    public int getSubtaskid() {
        return this.subtaskid;
    }
    
    public void setSubtaskid(int subtaskid) {
        this.subtaskid = subtaskid;
    }
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getSubtitle() {
        return this.subtitle;
    }
    
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }
    public String getSubdesc() {
        return this.subdesc;
    }
    
    public void setSubdesc(String subdesc) {
        this.subdesc = subdesc;
    }
    public String getActiondesc() {
        return this.actiondesc;
    }
    
    public void setActiondesc(String actiondesc) {
        this.actiondesc = actiondesc;
    }
    public Date getActiontime() {
        return this.actiontime;
    }
    
    public void setActiontime(Date actiontime) {
        this.actiontime = actiontime;
    }
    public Set<Tag> getTags() {
        return this.tags;
    }
    
    public void setTags(Set<Tag> tags) {
        this.tags = tags;
    }




}


