package com.proj.bean;
// Generated Nov 20, 2016 9:57:49 PM by Hibernate Tools 4.3.1



/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private int tagid;
     private SubTask subTask;
     private String tagname;
     private String tagcolorclass;

    public Tag() {
    }

    public Tag(int tagid, SubTask subTask, String tagname, String tagcolorclass) {
       this.tagid = tagid;
       this.subTask = subTask;
       this.tagname = tagname;
       this.tagcolorclass = tagcolorclass;
    }
   
    public int getTagid() {
        return this.tagid;
    }
    
    public void setTagid(int tagid) {
        this.tagid = tagid;
    }
    public SubTask getSubTask() {
        return this.subTask;
    }
    
    public void setSubTask(SubTask subTask) {
        this.subTask = subTask;
    }
    public String getTagname() {
        return this.tagname;
    }
    
    public void setTagname(String tagname) {
        this.tagname = tagname;
    }
    public String getTagcolorclass() {
        return this.tagcolorclass;
    }
    
    public void setTagcolorclass(String tagcolorclass) {
        this.tagcolorclass = tagcolorclass;
    }




}


