package com.proj.bean;
// Generated Nov 20, 2016 9:57:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userid;
     private String username;
     private String password;
     private String firstname;
     private String lastname;
     private String company;
     private String profilepic;
     private Set<Project> projects = new HashSet<Project>(0);
     private Set<SubTask> subTasks = new HashSet<SubTask>(0);
     private Set<ProjGroup> projGroups = new HashSet<ProjGroup>(0);

    public User() {
    }

	
    public User(int userid, String username, String password, String firstname, String lastname, String company) {
        this.userid = userid;
        this.username = username;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.company = company;
        this.profilepic = "images/man.jpg";
    }
    public User(int userid, String username, String password, String firstname, String lastname, String company, String profilepic) {
        this.userid = userid;
        this.username = username;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.company = company;
        this.profilepic = profilepic;
    }
    public User(int userid, String username, String password, String firstname, String lastname, String company, String profilepic, Set<Project> projects, Set<SubTask> subTasks, Set<ProjGroup> projGroups) {
       this.userid = userid;
       this.username = username;
       this.password = password;
       this.firstname = firstname;
       this.lastname = lastname;
       this.company = company;
       this.profilepic = profilepic;
       this.projects = projects;
       this.subTasks = subTasks;
       this.projGroups = projGroups;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getProfilepic() {
        return this.profilepic;
    }
    
    public void setProfilepic(String profilepic) {
        this.profilepic = profilepic;
    }
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }
    public Set<SubTask> getSubTasks() {
        return this.subTasks;
    }
    
    public void setSubTasks(Set<SubTask> subTasks) {
        this.subTasks = subTasks;
    }

    public Set<ProjGroup> getProjGroups() {
        return this.projGroups;
    }
    
    public void setProjGroups(Set<ProjGroup> projGroups) {
        this.projGroups = projGroups;
    }

    @Override
    public String toString() {
        return "User{" + "userid=" + userid + ", username=" + username + ", password=" + password + ", firstname=" + firstname + ", lastname=" + lastname + ", company=" + company + ", profilepic=" + profilepic + ", projects=" + projects + ", subTasks=" + subTasks + ", projGroups=" + projGroups + '}';
    }



}


